FORMAT: 1A
HOST: http://fleuriste.interflora.fr/proxyFrontOffice/api

# API SI Interflora => tablette

Documentation des web services rest

## Service de connexion [/loginTablette]

### Requete de connexion [POST]

+ Request (application/json)

        {
            "floristId": "1128",
            "password": "DVYTE"
        }

+ Response 201 (application/json)

    + Headers

            Location: /loginTablette

    + Body

            {
                "stusP": "1",
                "idAgent": "A10",
               "idProfile": "V",
               "passInterne": "agent10",
               "catalogueVille":    {
                  "url": "http://localhost:8080/catalogue/VILLE_20161222161253503.zip",
                  "modify_at": "2016-12-22 16:12:53"
               },
               "catalogueProduit":    {
                  "url": "http://localhost:8080/catalogue/PRODUIT_20170105155303322.zip",
                  "modify_at": "2017-01-05 15:53:03"
               },
               "info":    {
                  "rs": "INTERFLORA-P.DENAIN TEST",
                  "adr": "8, place des Vins de France ",
                  "codp": "75012",
                  "vill": "PARIS",
                  "telp": "0478955982"
               }
            }

## Compteur de numéros de commande [/compteur]

### Requete pour obtenir un numéro de commande [POST]

+ Request (application/json)

        {
            "prefix": "IF"
        }

+ Response 201 (application/json)

    + Headers

            Location: /compteur

    + Body

            {
                "numCmd": "IF00000001"
            }
            
## Transmission d'une commande de tablette => SI Interflora [/commande]

### Requete de transmission d'une command [POST]

+ Request (application/json)

        {
            "numeroTransmetteur" : "1128",
            "commandeId" : "IF00158785",
            "jetonCde" : "",
            "execChoisi" : "",
            "prixTotal" : "4680",
            "totalPromotions" : "???",
            "dateLivraison" : "20170212",
            "momentLivraison" : "J",
            "occasion" : "01",
            "messagePerso" : "mon message",
            "signature" : "ma signature",
            "client" : [
                {
                    "nom" : "nomClient",
                    "telephone1" : "0123456789",
                    "telephone2" : "0123456789,
                    "prenom" : "prenomClient",
                    "email" : "test@test.fr"
                }
            ],
            "destinataire" : [
                {
                    "natureAdresse" : "d",
                    "civilite" : "mr",
                    "nom" : "nomDestinataire",
                    "prenom" : "prenomDestinataire",
                    "telephone1" : "0123456789",
                    "telephone2" : "0123456789",
                    "adresse" : "adresseDest",
                    "ville" : "LYON 2",
                    "codePostal" : "69002",
                    "insee" : "69123102",
                    "infoComplementaire1",
                    "infoComplementaire2",
                    "batiment" : "B",
                    "etage" : "12",
                    "digicode" : "A123",
                    "porte" : "gauche"
                }
            ],
            "lignesCommande" : [
                {
                    "codeProduit" : "2BO",
                    "quantite" : "1",
                    "typeProduit" : "TABLETTE",
                    "tailleProduit" : "1",
                    "privex" : "2500"
                }
            ],
            "adresseIpNode" : "127.0.0.1",
            "userAgent" : "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0",
            "employee" : "Magasin 1"
        }

+ Response 201 (application/json)

    + Headers

            Location: /commande

    + Body

            {
                "timeStampCommande" : "2017-02-10T15:50:00",
            }

## Service de faisabilité de commande [/faisabilite]

### Requete d'intérogation de la faisablilité d'une commande[POST]

+ Request (application/json)

        {
            "codePostal" : "",
            "codeProduitSku" : "",
            "dateLivraison" : "",
            "horaire" : "",
            "insee" : "",
            "listeAccessoiresSku" :""

+ Response 201 (application/json)

    + Headers

            Location: /faisabilite

    + Body

            {
                "codeErreur" : "",
                "libelleErreur" : "",
                "jetonCommande" : "",
                "listeDesExecutants",
                "accessoiresPossibles", ""
            }