FORMAT: 1A
HOST: http://fleuriste.interflora.fr/proxyFrontOffice/api

# tablette

Documentation des web services rest

## Service de connexion [/loginTablette]

### Requete de connexion [POST]

+ Request (application/json)

        {
            "floristId": "Numéro de membre du fleuriste",
            "password": "Mot de passe"
        }

+ Response 201 (application/json)

    + Headers

            Location: /loginTablette

    + Body

            {
                "stusP": "Réponse principale du WS (0 ou 1)",
                "stusS": "Raison de la non autorisation d'acces (de 0 à 5)",
                "idAgent": "idAgent",
                "idProfile": "V (vendeur) M (manager)",
                "passInterne": "Rappel du mot de passe",
                "info": "Partie informations sur le fleuriste. A completter si necessaire"
                {
                    "rs": "Raison sociale du fleuriste"
                }
            }

## Compteur de numéros de commande [/compteur]

### Requete pour obtenir un numéro de commande [POST]

+ Request (application/json)

        {
            "prefix": "Préfix du numéro de commande. Non obligatoire. On utilise IF si prefix n'est pas definit.",
        }

+ Response 201 (application/json)

    + Headers

            Location: /compteur

    + Body

            {
                "numCmd": "Numéro de commande de la forme XXNNNNNNNN avec NN = prefix envoyé dans la requete (IF si non présent), et XXXXXXXX = compteur numérique sur 8 chiffres."
            }
            
## Transmission d'une commande de tablette => Si Interflora [/commande]

### Requete pour obtenir un numéro de commande [POST]

+ Request (application/json)

        {
            "numeroTransmetteur",
            "commandeId",
            "jetonCde",
            "execChoisi",
            "prixTotal",
            "prixLivraison",
            "totalPromotions",
            "dateLivraison",
            "momentLivraison",
            "occasion",
            "messagePerso",
            "signature",
            "client" : [
                {
                    "nom",
                    "telephone1",
                    "telephone2",
                    "prenom",
                    "email"
                }
            ],
            "destinataire" : [
                {
                    "natureAdresse",
                    "civilite",
                    "nom",
                    "prenom",
                    "telephone1",
                    "telephone2",
                    "adresse",
                    "ville",
                    "codePostal",
                    "insee",
                    "infoComplementaire1",
                    "infoComplementaire2",
                    "batiment",
                    "etage",
                    "digicode",
                    "porte"
                }
            ],
            "lignesCommande" : [
                {
                    "codeProduit",
                    "libelle",
                    "quantite",
                    "prixVariante",
                    "prix",
                    "fraisReseau",
                    "typeProduit",
                    "privex",
                    "complementPrixMarketing",
                    "complementPrixInterflora",
                    "tailleProduit"
                }
            ],
            "adresseIpNode",
            "userAgent",
            "employee"
        }

+ Response 201 (application/json)

    + Headers

            Location: /compteur

    + Body

            {
                "reponse" : "reponse"
            }